//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choice
    {
        public int ch_id { get; set; }
        public int Quset_id { get; set; }
        public string choices { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
