//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public int T_id { get; set; }
        public Nullable<int> C_id { get; set; }
        public string Name { get; set; }
    
        public virtual course course { get; set; }
    }
}
